### ISSUE TITLE
Feature Request: make HUD Place Like Scoreboard in PC

### ISSUE THREAD

**Issue by FuxonPlayz** [FaigerSYS/superBAR#13]
Hi There!
I want to ask if u can add a way to make the HUD on the right like PC

Sorry for bad English 😞

**Comment by FaigerSYS** [comment]
Can you send me a screenshot of how it should look?

**Comment by FaigerSYS** [comment]
If u want to make HUD on right, use "text-offset-level". Please read ALL config before asking for "new features"

**Comment by FaigerSYS** [comment]
If your problem is solved please close issue
