### ISSUE TITLE
Auto Enable

### ISSUE THREAD

**Issue by buchwasa** [FaigerSYS/superBAR#15]
Auto enable no longer works with the new updates.

**Comment by FaigerSYS** [comment]
I know. This is maybe PurePerms (I'm not sure) issue. When checking for a permission, it return false. But, not for all players :\

**Comment by VCraftMCPE** [comment]
Dood won't works here

**Comment by xXRyzen** [comment]
I have tested and verified that the conflicting plugin is SimpleAuth. @FaigerSYS @TheAppleGamer @VCraftMCPE hopefully its a lead towards a fix? :)

**Comment by xXRyzen** [comment]
I switched to PAuth for now. working fine!

**Comment by FaigerSYS** [comment]
Finally reproduced! Thanks @FienixEC 😆 . Will be fixed soon

**Comment by FaigerSYS** [comment]
Fixed in 1.6.0

**Comment by xXRyzen** [comment]
Np! @FaigerSYS glad i could help as i LOVE this plugin!!!! :)

**Comment by xXRyzen** [comment]
btw, @VCraftMCPE @TheAppleGamer  @erkam2002  dont use PAuth. it sucks and is not secure, i learned the hard way lol, with that, done posting un related comments! :)

**Comment by buchwasa** [comment]
Oh hey it's fixed! I should've fixed it myself but I was a noob back in August :3
