### ISSUE TITLE
Bar not work..

### ISSUE THREAD

**Issue by DarkEtch** [FaigerSYS/superBAR#19]
![screenshot_2016-11-15-06-04-05](https://cloud.githubusercontent.com/assets/23136453/20293787/796fd654-aaf9-11e6-87bd-a3818c6f4ca9.png)

**Comment by FaigerSYS** [comment]
Can you send your config?

**Comment by FaigerSYS** [comment]
Fixed in [v.1.6.1](https://github.com/FaigerSYS/superBAR/releases/tag/v.1.6.1)
