### ISSUE TITLE
Error in console and faction gametime not showing since update

### ISSUE THREAD

**Issue by kabluinc** [FaigerSYS/superBAR#20]
Since the update of the plugin, many things arnt working. Firstly the faction doesnt show up in the hud and gametime shows no Plug although gametime is installed and i can still do /gt all. All worked perfectly before the update.

This error keeps spamming on the console

Notice: Undefined variable: fact in C:\Users\Gamer27832 server\Desktop\plugins\plugins\superBAR-master\src\FaigerSYS\superBAR\core\HUD.php on line 74

Notice: Undefined index: no-faction in C:\Users\Gamer27832 server\Desktop\plugins\plugins\superBAR-master\src\FaigerSYS\superBAR\core\HUD.php on line 75

**Comment by FaigerSYS** [comment]
[superBAR v.1.6.2](https://github.com/FaigerSYS/superBAR/releases/tag/v.1.6.2)

**Comment by kabluinc** [comment]
Hi,

Thanks for the quick response. Faction display is now fixed however GameTime still shows no plugin on HUD. although at startup it says GameTime ok! meaning its loaded
