### ISSUE TITLE
Micro-forum

### ISSUE THREAD

**Issue by FaigerSYS** [FaigerSYS/superBAR#4]
**There you can ask me something about this plugin.**
_If you have issue - create a new issue post!_

**Comment by ghost** [comment]
Good job :)

**Comment by Erkam246** [comment]
Can you add ping status

**Comment by Erkam246** [comment]
With %PING%

**Comment by FaigerSYS** [comment]
@erkam2002 , ping from player to server?

**Comment by Erkam246** [comment]
Yes

**Comment by Erkam246** [comment]
Ping from player

**Comment by FaigerSYS** [comment]
@erkam2002 , I'm not sure I know how to get the user's phone to send a ping to the server and send the result of the ping to server

**Comment by Erkam246** [comment]
:,(

**Comment by Erkam246** [comment]
Are you online @FaigerSYS ?

**Comment by Erkam246** [comment]
@FaigerSYS   ???

**Comment by FaigerSYS** [comment]
@erkam2002 , yes.

**Comment by Erkam246** [comment]
Can i create a Adfly link? To download superbar?

**Comment by FaigerSYS** [comment]
No

**Comment by Erkam246** [comment]
I have found a method to get ping :  
$tB = microtime(true);
$socket = fSockOpen($player->getAddress(), 80, $errno, $errstr, 10);
if(!($socket)) {
  $this->getServer()->getLogger()->info($player->getAddress() . " was uncreachable.");
}
$tA = microtime(true);
$ping = round((($tA - $tB) \* 1000), 0);
$this->getServer()->getLogger()->info("Ping of " . $player->getAddress() . " was: " . $ping . ".ms");

**Comment by FaanMaario** [comment]
Hi, I and my players love your plugin !
I have a suggestion, can you add a command for the players to disable the superbar?
It could be very useful for my pvp faction, for players who want to record without show their cords :)

**Comment by Erkam246** [comment]
Can you implement ping in superbar

**Comment by FaigerSYS** [comment]
@FaanMaario , OK :)

**Comment by FaigerSYS** [comment]
@erkam2002 , if I have time - I will test and add it

**Comment by Erkam246** [comment]
Kk

**Comment by FaanMaario** [comment]
Thank you @FaigerSYS !

**Comment by FaigerSYS** [comment]
@FaanMaario , check [superBAR v.1.5.1](https://github.com/FaigerSYS/superBAR/releases/tag/1.5.1) ;)

**Comment by FaanMaario** [comment]
@FaigerSYS Thank you a lot ! You're the best !

**Comment by FaanMaario** [comment]
But, the default-enabled setting don't work.
I set to "true" but on join, players don't have the bar :/

**Comment by FaigerSYS** [comment]
Try to set without "". Like here
![screenshot_2016-07-14-06-44-56 01](https://cloud.githubusercontent.com/assets/18305374/16827370/b2d85fdc-498e-11e6-971e-0137c72881e5.png)

**Comment by FaigerSYS** [comment]
@FaanMaario, try to set without "". Like here
![screenshot_2016-07-14-06-44-56 01](https://cloud.githubusercontent.com/assets/18305374/16827370/b2d85fdc-498e-11e6-971e-0137c72881e5.png)

**Comment by FaanMaario** [comment]
@FaigerSYS But it's already like that, and I tried with the ""; nothing. :/

**Comment by FaigerSYS** [comment]
@FaanMaario , try this version. Please tell me whether the error is corrected. 
https://github.com/FaigerSYS/superBAR_additionally/raw/master/superBAR_v1.5.2_Test.phar

**Comment by FaigerSYS** [comment]
@FaanMaario , try this version. Please tell me if the error is corrected or not.
https://github.com/FaigerSYS/superBAR_additionally/raw/master/superBAR_v1.5.2_Test.phar

**Comment by FaanMaario** [comment]
@FaigerSYS Tried and not working :/
Should I update the config.yml?

**Comment by CLiu13** [comment]
Having the HUD enable//disable bug as well.

Also, using \n in groups.yml does not work. On /sb reload, all \n's in groups.yml are replaced with actual new lines, but it does not show up on the in-game HUD. This does not occur with config.yml.

**Comment by FaigerSYS** [comment]
@FaanMaario , try to start superBAR without PurePerms. Also, try add to users "superbar.use" permission.

**Comment by FaigerSYS** [comment]
@CLiu13 , update will be soon

**Comment by Akuroma** [comment]
Could you add a addon for purechat like %pure_chat% or something like that. Than the ranks would also have the colors :)

**Comment by VCraftMCPE** [comment]
It won't works for me

**Comment by alexbgameson** [comment]
This plugin no longer works with genisys.

Stoped working after genisys 16.0 update

**Comment by FaigerSYS** [comment]
#17

**Comment by ghost** [comment]
Hi, how to create a %MONEY% ?

**Comment by FaigerSYS** [comment]
@GamingPilot2 what do you mean?

**Comment by FaigerSYS** [comment]
[superBAR v.1.6.1](https://github.com/FaigerSYS/superBAR/releases/tag/v.1.6.1)

**Comment by SuperDude36** [comment]
Can you make it so you can move the hud up and down as well as left and right?

**Comment by Arantxia** [comment]
Can I ask how do people moved their bar up ward? Cuz tip just raised it a little bit and idk how do i move the HUD Upwar anymore :/

**Comment by FaigerSYS** [comment]
Add some \n to the end of format. I will make specific property for this in future

**Comment by arsenicblast** [comment]
How to add line ? I mean I want hud like this


   welcome to (server name)
  player: ()/()     faction : 

Cant add a line tho,I dont know what to write to add

**Comment by FaigerSYS** [comment]
@arsenicblast , everything described in config
