### ISSUE TITLE
Undefined Index

### ISSUE THREAD

**Issue by ClockProgramming** [FaigerSYS/superBAR#5]
Well, undefined index are showing when starting up the server
# Logs

Warning: yaml_parse(): reading error encountered during parsing: control characters are not allowed (line 1, column 1) in phar://C:/Users/glitc/Desktop/Wyvern High/Genisys.phar/src/pocketmine/utils/Config.php on line 143

Warning: yaml_parse(): reading error encountered during parsing: control characters are not allowed (line 1, column 1) in phar://C:/Users/glitc/Desktop/Wyvern High/Genisys.phar/src/pocketmine/utils/Config.php on line 143

Warning: yaml_parse(): reading error encountered during parsing: control characters are not allowed (line 1, column 1) in phar://C:/Users/glitc/Desktop/Wyvern High/Genisys.phar/src/pocketmine/utils/Config.php on line 143

Notice: Undefined index: Guest in phar://C:/Users/glitc/Desktop/Wyvern High/plugins/superBAR_v1.4.10.phar/src/FaigerSYS/superBAR/ConfigProvider.php on line 44

Notice: Undefined index: time-format in phar://C:/Users/glitc/Desktop/Wyvern High/plugins/superBAR_v1.4.10.phar/src/FaigerSYS/superBAR/ConfigProvider.php on line 45

Notice: Undefined index: no-faction in phar://C:/Users/glitc/Desktop/Wyvern High/plugins/superBAR_v1.4.10.phar/src/FaigerSYS/superBAR/ConfigProvider.php on line 46

Notice: Undefined index: type in phar://C:/Users/glitc/Desktop/Wyvern High/plugins/superBAR_v1.4.10.phar/src/FaigerSYS/superBAR/ConfigProvider.php on line 48

Notice: Undefined index: text-offset-level in phar://C:/Users/glitc/Desktop/Wyvern High/plugins/superBAR_v1.4.10.phar/src/FaigerSYS/superBAR/ConfigProvider.php on line 53

Notice: Undefined index: Admin in phar://C:/Users/glitc/Desktop/Wyvern High/plugins/superBAR_v1.4.10.phar/src/FaigerSYS/superBAR/ConfigProvider.php on line 44

Notice: Undefined index: time-format in phar://C:/Users/glitc/Desktop/Wyvern High/plugins/superBAR_v1.4.10.phar/src/FaigerSYS/superBAR/ConfigProvider.php on line 45

Notice: Undefined index: no-faction in phar://C:/Users/glitc/Desktop/Wyvern High/plugins/superBAR_v1.4.10.phar/src/FaigerSYS/superBAR/ConfigProvider.php on line 46

Notice: Undefined index: type in phar://C:/Users/glitc/Desktop/Wyvern High/plugins/superBAR_v1.4.10.phar/src/FaigerSYS/superBAR/ConfigProvider.php on line 48

Notice: Undefined index: text-offset-level in phar://C:/Users/glitc/Desktop/Wyvern High/plugins/superBAR_v1.4.10.phar/src/FaigerSYS/superBAR/ConfigProvider.php on line 53

Notice: Undefined index: Owner in phar://C:/Users/glitc/Desktop/Wyvern High/plugins/superBAR_v1.4.10.phar/src/FaigerSYS/superBAR/ConfigProvider.php on line 44

Notice: Undefined index: time-format in phar://C:/Users/glitc/Desktop/Wyvern High/plugins/superBAR_v1.4.10.phar/src/FaigerSYS/superBAR/ConfigProvider.php on line 45

Notice: Undefined index: no-faction in phar://C:/Users/glitc/Desktop/Wyvern High/plugins/superBAR_v1.4.10.phar/src/FaigerSYS/superBAR/ConfigProvider.php on line 46

Notice: Undefined index: type in phar://C:/Users/glitc/Desktop/Wyvern High/plugins/superBAR_v1.4.10.phar/src/FaigerSYS/superBAR/ConfigProvider.php on line 48

Notice: Undefined index: text-offset-level in phar://C:/Users/glitc/Desktop/Wyvern High/plugins/superBAR_v1.4.10.phar/src/FaigerSYS/superBAR/ConfigProvider.php on line 53

Notice: Undefined index: OP in phar://C:/Users/glitc/Desktop/Wyvern High/plugins/superBAR_v1.4.10.phar/src/FaigerSYS/superBAR/ConfigProvider.php on line 44

Notice: Undefined index: time-format in phar://C:/Users/glitc/Desktop/Wyvern High/plugins/superBAR_v1.4.10.phar/src/FaigerSYS/superBAR/ConfigProvider.php on line 45

Notice: Undefined index: no-faction in phar://C:/Users/glitc/Desktop/Wyvern High/plugins/superBAR_v1.4.10.phar/src/FaigerSYS/superBAR/ConfigProvider.php on line 46

Notice: Undefined index: type in phar://C:/Users/glitc/Desktop/Wyvern High/plugins/superBAR_v1.4.10.phar/src/FaigerSYS/superBAR/ConfigProvider.php on line 48

Notice: Undefined index: text-offset-level in phar://C:/Users/glitc/Desktop/Wyvern High/plugins/superBAR_v1.4.10.phar/src/FaigerSYS/superBAR/ConfigProvider.php on line 53

Notice: Undefined index: §3Main▒lMain§4Owner§7 in phar://C:/Users/glitc/Desktop/Wyvern High/plugins/superBAR_v1.4.10.phar/src/FaigerSYS/superBAR/ConfigProvider.php on line 44

Notice: Undefined index: time-format in phar://C:/Users/glitc/Desktop/Wyvern High/plugins/superBAR_v1.4.10.phar/src/FaigerSYS/superBAR/ConfigProvider.php on line 45

Notice: Undefined index: no-faction in phar://C:/Users/glitc/Desktop/Wyvern High/plugins/superBAR_v1.4.10.phar/src/FaigerSYS/superBAR/ConfigProvider.php on line 46

Notice: Undefined index: type in phar://C:/Users/glitc/Desktop/Wyvern High/plugins/superBAR_v1.4.10.phar/src/FaigerSYS/superBAR/ConfigProvider.php on line 48

Notice: Undefined index: text-offset-level in phar://C:/Users/glitc/Desktop/Wyvern High/plugins/superBAR_v1.4.10.phar/src/FaigerSYS/superBAR/ConfigProvider.php on line 53

Notice: Undefined index: §3§lMain§4Owner§7 in phar://C:/Users/glitc/Desktop/Wyvern High/plugins/superBAR_v1.4.10.phar/src/FaigerSYS/superBAR/ConfigProvider.php on line 44

Notice: Undefined index: time-format in phar://C:/Users/glitc/Desktop/Wyvern High/plugins/superBAR_v1.4.10.phar/src/FaigerSYS/superBAR/ConfigProvider.php on line 45

Notice: Undefined index: no-faction in phar://C:/Users/glitc/Desktop/Wyvern High/plugins/superBAR_v1.4.10.phar/src/FaigerSYS/superBAR/ConfigProvider.php on line 46

Notice: Undefined index: type in phar://C:/Users/glitc/Desktop/Wyvern High/plugins/superBAR_v1.4.10.phar/src/FaigerSYS/superBAR/ConfigProvider.php on line 48

Notice: Undefined index: text-offset-level in phar://C:/Users/glitc/Desktop/Wyvern High/plugins/superBAR_v1.4.10.phar/src/FaigerSYS/superBAR/ConfigProvider.php on line 53

Notice: Undefined index: §6Own§5er§7 in phar://C:/Users/glitc/Desktop/Wyvern High/plugins/superBAR_v1.4.10.phar/src/FaigerSYS/superBAR/ConfigProvider.php on line 44

Notice: Undefined index: time-format in phar://C:/Users/glitc/Desktop/Wyvern High/plugins/superBAR_v1.4.10.phar/src/FaigerSYS/superBAR/ConfigProvider.php on line 45

Notice: Undefined index: no-faction in phar://C:/Users/glitc/Desktop/Wyvern High/plugins/superBAR_v1.4.10.phar/src/FaigerSYS/superBAR/ConfigProvider.php on line 46

Notice: Undefined index: type in phar://C:/Users/glitc/Desktop/Wyvern High/plugins/superBAR_v1.4.10.phar/src/FaigerSYS/superBAR/ConfigProvider.php on line 48

Notice: Undefined index: text-offset-level in phar://C:/Users/glitc/Desktop/Wyvern High/plugins/superBAR_v1.4.10.phar/src/FaigerSYS/superBAR/ConfigProvider.php on line 53

Notice: Undefined index: §3§lOw§4ner in phar://C:/Users/glitc/Desktop/Wyvern High/plugins/superBAR_v1.4.10.phar/src/FaigerSYS/superBAR/ConfigProvider.php on line 44

Notice: Undefined index: time-format in phar://C:/Users/glitc/Desktop/Wyvern High/plugins/superBAR_v1.4.10.phar/src/FaigerSYS/superBAR/ConfigProvider.php on line 45

Notice: Undefined index: no-faction in phar://C:/Users/glitc/Desktop/Wyvern High/plugins/superBAR_v1.4.10.phar/src/FaigerSYS/superBAR/ConfigProvider.php on line 46

Notice: Undefined index: type in phar://C:/Users/glitc/Desktop/Wyvern High/plugins/superBAR_v1.4.10.phar/src/FaigerSYS/superBAR/ConfigProvider.php on line 48

Notice: Undefined index: text-offset-level in phar://C:/Users/glitc/Desktop/Wyvern High/plugins/superBAR_v1.4.10.phar/src/FaigerSYS/superBAR/ConfigProvider.php on line 53

Notice: Undefined index: §3§lHead§4Admin in phar://C:/Users/glitc/Desktop/Wyvern High/plugins/superBAR_v1.4.10.phar/src/FaigerSYS/superBAR/ConfigProvider.php on line 44

Notice: Undefined index: time-format in phar://C:/Users/glitc/Desktop/Wyvern High/plugins/superBAR_v1.4.10.phar/src/FaigerSYS/superBAR/ConfigProvider.php on line 45

Notice: Undefined index: no-faction in phar://C:/Users/glitc/Desktop/Wyvern High/plugins/superBAR_v1.4.10.phar/src/FaigerSYS/superBAR/ConfigProvider.php on line 46

Notice: Undefined index: type in phar://C:/Users/glitc/Desktop/Wyvern High/plugins/superBAR_v1.4.10.phar/src/FaigerSYS/superBAR/ConfigProvider.php on line 48

Notice: Undefined index: text-offset-level in phar://C:/Users/glitc/Desktop/Wyvern High/plugins/superBAR_v1.4.10.phar/src/FaigerSYS/superBAR/ConfigProvider.php on line 53

Notice: Undefined index: §l§3Ow§4ner in phar://C:/Users/glitc/Desktop/Wyvern High/plugins/superBAR_v1.4.10.phar/src/FaigerSYS/superBAR/ConfigProvider.php on line 44

Notice: Undefined index: time-format in phar://C:/Users/glitc/Desktop/Wyvern High/plugins/superBAR_v1.4.10.phar/src/FaigerSYS/superBAR/ConfigProvider.php on line 45

Notice: Undefined index: no-faction in phar://C:/Users/glitc/Desktop/Wyvern High/plugins/superBAR_v1.4.10.phar/src/FaigerSYS/superBAR/ConfigProvider.php on line 46

Notice: Undefined index: type in phar://C:/Users/glitc/Desktop/Wyvern High/plugins/superBAR_v1.4.10.phar/src/FaigerSYS/superBAR/ConfigProvider.php on line 48

Notice: Undefined index: text-offset-level in phar://C:/Users/glitc/Desktop/Wyvern High/plugins/superBAR_v1.4.10.phar/src/FaigerSYS/superBAR/ConfigProvider.php on line 53

**Comment by alex2534alex** [comment]
Can u send me your config? File, not text

**Comment by FaigerSYS** [comment]
@GlitchPlayer , can u send me your config? File, not text

**Comment by FaigerSYS** [comment]
I think that you use the wrong encoding. It must be UTF-8

**Comment by FaigerSYS** [comment]
Can u answer me?

**Comment by ClockProgramming** [comment]
It got fixed when I saved it as UTF. sorry

**Comment by FaigerSYS** [comment]
No problems))
